spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: zildeus
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true