spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: zildeus
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
jwt:
  private-key: classpath:certs/privateKey.pem
  public-key: classpath:certs/publicKey.pem